services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/innersense

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend

  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Smartchoice1!
      POSTGRES_DB: innersense
    volumes:
      - postgres_data:/var/lib/postgresql/data

#  etl:
#    build: ./etl
#    container_name: etl
#    volumes:
#      - ./etl/data:/app/data  # Mounts data for local testing
          
volumes:
  postgres_data: