name: Deploy AWS Glue Scripts

on:
  push:
    branches:
      - main  # Runs when code is pushed to main branch
    paths:
      - "etl/app/glue_jobs/**"  # Runs only if Glue scripts are updated

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2  # Change if using a different region

      - name: Deploy AWS Glue Scripts to S3
        run: bash etl/deploy.sh
